#!/bin/bash
#Launcher for PMIRU. 
export KIVY_NO_ARGS=0

cd /
cd /home/pi/PMiru
lxterminal -e "python pmiru.py -m ; bash" 

#if no arguments start minimized
#if [ -z "$*" ]; then python pmiru.py; fi

#if -m start maximized
#if [ $1 == "-m" ]; then python pmiru.py -m; fi
